#include <idt.h>
#include <console.h>
#include <pic.h>
#include <string.h>
#include <gdt.h>
#include <klib.h>

#define ATTR __attribute__((packed))

typedef struct {
	uint16_t size;
	uint32_t addr;
} ATTR IDTR;

typedef struct {
	uint16_t 	addr_low;
	uint16_t 	selector;
	uint8_t 	zero;
	uint8_t 	flags;
	uint16_t 	addr_high;
} ATTR IDTDesc;

_Static_assert(sizeof(IDTR) 	== 6, "IDTR size not 6");
_Static_assert(sizeof(IDTDesc)	== 8, "IDTDesc size not 8");

#define MAX_INTERRUPTS 	(256)

static IDTR 	_idtr;
static IDTDesc 	_idt[MAX_INTERRUPTS];

//idt_asm.asm
void lidt(IDTR *idtr);

static void idt_set_gate(size_t num, uint32_t isr) {

	IDTDesc *desc = &_idt[num];
	
	desc->addr_low 	= isr & 0xffff;
	desc->selector 	= K_CODE_SEL;
	desc->zero 		= 0;
	desc->flags 	= 0b11101110;
	desc->addr_high = (isr >> 16) & 0xffff;
}

#define I_PAGE_FAULT	(14)

#define PF_P	(1 << 0)
#define PF_W	(1 << 1)
#define PF_U	(1 << 2)
#define PF_R	(1 << 3)
#define PF_I	(1 << 4)

static void pf_handler(trapframe_t *tf) {

	kprintfln("*** %x", read_cr2());
	
	kprintfln("- %s", tf->err_code & (1 << 0) ? 
		"caused by a protection violation" :
		"caused by a non-present page");
	
	kprintfln("- %s", tf->err_code & (1 << 1) ? 
		"write access caused the fault" :
		"read access caused the fault");
	
	kprintfln("- %s", tf->err_code & (1 << 2) ? 
		"the fault occurred in user mode" :
		"the fault occurred in supervisor  mode");
	
	kprintfln("- %s", tf->err_code & (1 << 3) ? 
		"one or more page directory entries contain reserved bits which are set to 1" :
		"This only applies when the PSE or PAE flags in CR4 are set to 1");
	
	kprintfln("- %s", tf->err_code & (1 << 4) ? 
		"the fault was caused by an instruction fetch" :
		"This only applies when the No-Execute bit is supported and enabled");
	
	panic("*** page fault");
}

static void gpf_handler(trapframe_t *tf) {
	kprintfln("*** eip: %x", tf->eip);
	kprintfln("*** seg: %x", tf->err_code);
	panic("*** General Protection Fault");
}

#define I_GP_FAULT 		(13)

typedef  void (*isr_wrapper_t)();
static isr_wrapper_t ISR_WRAPPERS[MAX_INTERRUPTS];

static isr_t ISRS[MAX_INTERRUPTS];

void set_isr(int num, isr_t isr) {
	ISRS[num] = isr;
}

void init_idt() {
		
	for (size_t i = 0; i < MAX_INTERRUPTS; i++)
		idt_set_gate(i, (uint32_t)ISR_WRAPPERS[i]);
	
	_idtr.size = sizeof(IDTDesc) * MAX_INTERRUPTS - 1;
	_idtr.addr = (uint32_t)&_idt;
	
	lidt(&_idtr);
	
	set_isr(I_PAGE_FAULT, pf_handler);
	set_isr(I_GP_FAULT, gpf_handler);
}

static char is_irq_master(uint32_t num) {
	if (num >= 32 && num < 40)
		return 1;
	return 0;
}

static char is_irq_slave(uint32_t num) {
	if (num >= 40 && num < 48)
		return 1;
	return 0;
}

static char is_irq_spurious(uint32_t num) {
	
	if (num == IRQ_BASE + IRQ_SPURIOUS_MASTER) {
	
		if (pic_isr(PIC_MASTER) & IRQ_SPURIOUS_MASTER) {
			//legit
			kprintfln("*** legit spurious master irq!");
		} else {
			//spurious
			kprintfln("*** spurious master irq!");
			return 1;
		}
		
	} else if (num == IRQ_BASE + IRQ_SPURIOUS_SLAVE) {
	
		if (pic_isr(PIC_SLAVE) & (IRQ_SPURIOUS_SLAVE >> 8)) {
			//legit
			kprintfln("*** legit spurious slave irq!");
		} else {
			//spurious
			kprintfln("*** spurious slave irq!");
			return 1;
		}
	}
	
	return 0;
}

void isr_common(trapframe_t *tf) {
	
	//irq spurious
	if (is_irq_spurious(tf->num)) {
		if (is_irq_slave(tf->num))
			pic_eoi(PIC_MASTER);
		return;
	}
	
	//irq eoi
	if (is_irq_slave(tf->num))
		pic_eoi(PIC_SLAVE);
	if (is_irq_master(tf->num))
		pic_eoi(PIC_MASTER);
	
	isr_t isr = ISRS[tf->num];
	if (isr == 0) {
		kprintfln("*** unhandled int: %d", tf->num);
		panic("*** panic");
	} else {
		isr(tf);
	}
}

#define ISR_WRAPPER_NAME(num) isr_wrapper_##num
#define ISR_WRAPPER_DECL(num) void ISR_WRAPPER_NAME(num)()

ISR_WRAPPER_DECL(0);
ISR_WRAPPER_DECL(1);
ISR_WRAPPER_DECL(2);
ISR_WRAPPER_DECL(3);
ISR_WRAPPER_DECL(4);
ISR_WRAPPER_DECL(5);
ISR_WRAPPER_DECL(6);
ISR_WRAPPER_DECL(7);
ISR_WRAPPER_DECL(8);
ISR_WRAPPER_DECL(9);
ISR_WRAPPER_DECL(10);
ISR_WRAPPER_DECL(11);
ISR_WRAPPER_DECL(12);
ISR_WRAPPER_DECL(13);
ISR_WRAPPER_DECL(14);
ISR_WRAPPER_DECL(15);
ISR_WRAPPER_DECL(16);
ISR_WRAPPER_DECL(17);
ISR_WRAPPER_DECL(18);
ISR_WRAPPER_DECL(19);
ISR_WRAPPER_DECL(20);
ISR_WRAPPER_DECL(21);
ISR_WRAPPER_DECL(22);
ISR_WRAPPER_DECL(23);
ISR_WRAPPER_DECL(24);
ISR_WRAPPER_DECL(25);
ISR_WRAPPER_DECL(26);
ISR_WRAPPER_DECL(27);
ISR_WRAPPER_DECL(28);
ISR_WRAPPER_DECL(29);
ISR_WRAPPER_DECL(30);
ISR_WRAPPER_DECL(31);
ISR_WRAPPER_DECL(32);
ISR_WRAPPER_DECL(33);
ISR_WRAPPER_DECL(34);
ISR_WRAPPER_DECL(35);
ISR_WRAPPER_DECL(36);
ISR_WRAPPER_DECL(37);
ISR_WRAPPER_DECL(38);
ISR_WRAPPER_DECL(39);
ISR_WRAPPER_DECL(40);
ISR_WRAPPER_DECL(41);
ISR_WRAPPER_DECL(42);
ISR_WRAPPER_DECL(43);
ISR_WRAPPER_DECL(44);
ISR_WRAPPER_DECL(45);
ISR_WRAPPER_DECL(46);
ISR_WRAPPER_DECL(47);
ISR_WRAPPER_DECL(48);
ISR_WRAPPER_DECL(49);
ISR_WRAPPER_DECL(50);
ISR_WRAPPER_DECL(51);
ISR_WRAPPER_DECL(52);
ISR_WRAPPER_DECL(53);
ISR_WRAPPER_DECL(54);
ISR_WRAPPER_DECL(55);
ISR_WRAPPER_DECL(56);
ISR_WRAPPER_DECL(57);
ISR_WRAPPER_DECL(58);
ISR_WRAPPER_DECL(59);
ISR_WRAPPER_DECL(60);
ISR_WRAPPER_DECL(61);
ISR_WRAPPER_DECL(62);
ISR_WRAPPER_DECL(63);
ISR_WRAPPER_DECL(64);
ISR_WRAPPER_DECL(65);
ISR_WRAPPER_DECL(66);
ISR_WRAPPER_DECL(67);
ISR_WRAPPER_DECL(68);
ISR_WRAPPER_DECL(69);
ISR_WRAPPER_DECL(70);
ISR_WRAPPER_DECL(71);
ISR_WRAPPER_DECL(72);
ISR_WRAPPER_DECL(73);
ISR_WRAPPER_DECL(74);
ISR_WRAPPER_DECL(75);
ISR_WRAPPER_DECL(76);
ISR_WRAPPER_DECL(77);
ISR_WRAPPER_DECL(78);
ISR_WRAPPER_DECL(79);
ISR_WRAPPER_DECL(80);
ISR_WRAPPER_DECL(81);
ISR_WRAPPER_DECL(82);
ISR_WRAPPER_DECL(83);
ISR_WRAPPER_DECL(84);
ISR_WRAPPER_DECL(85);
ISR_WRAPPER_DECL(86);
ISR_WRAPPER_DECL(87);
ISR_WRAPPER_DECL(88);
ISR_WRAPPER_DECL(89);
ISR_WRAPPER_DECL(90);
ISR_WRAPPER_DECL(91);
ISR_WRAPPER_DECL(92);
ISR_WRAPPER_DECL(93);
ISR_WRAPPER_DECL(94);
ISR_WRAPPER_DECL(95);
ISR_WRAPPER_DECL(96);
ISR_WRAPPER_DECL(97);
ISR_WRAPPER_DECL(98);
ISR_WRAPPER_DECL(99);
ISR_WRAPPER_DECL(100);
ISR_WRAPPER_DECL(101);
ISR_WRAPPER_DECL(102);
ISR_WRAPPER_DECL(103);
ISR_WRAPPER_DECL(104);
ISR_WRAPPER_DECL(105);
ISR_WRAPPER_DECL(106);
ISR_WRAPPER_DECL(107);
ISR_WRAPPER_DECL(108);
ISR_WRAPPER_DECL(109);
ISR_WRAPPER_DECL(110);
ISR_WRAPPER_DECL(111);
ISR_WRAPPER_DECL(112);
ISR_WRAPPER_DECL(113);
ISR_WRAPPER_DECL(114);
ISR_WRAPPER_DECL(115);
ISR_WRAPPER_DECL(116);
ISR_WRAPPER_DECL(117);
ISR_WRAPPER_DECL(118);
ISR_WRAPPER_DECL(119);
ISR_WRAPPER_DECL(120);
ISR_WRAPPER_DECL(121);
ISR_WRAPPER_DECL(122);
ISR_WRAPPER_DECL(123);
ISR_WRAPPER_DECL(124);
ISR_WRAPPER_DECL(125);
ISR_WRAPPER_DECL(126);
ISR_WRAPPER_DECL(127);
ISR_WRAPPER_DECL(128);
ISR_WRAPPER_DECL(129);
ISR_WRAPPER_DECL(130);
ISR_WRAPPER_DECL(131);
ISR_WRAPPER_DECL(132);
ISR_WRAPPER_DECL(133);
ISR_WRAPPER_DECL(134);
ISR_WRAPPER_DECL(135);
ISR_WRAPPER_DECL(136);
ISR_WRAPPER_DECL(137);
ISR_WRAPPER_DECL(138);
ISR_WRAPPER_DECL(139);
ISR_WRAPPER_DECL(140);
ISR_WRAPPER_DECL(141);
ISR_WRAPPER_DECL(142);
ISR_WRAPPER_DECL(143);
ISR_WRAPPER_DECL(144);
ISR_WRAPPER_DECL(145);
ISR_WRAPPER_DECL(146);
ISR_WRAPPER_DECL(147);
ISR_WRAPPER_DECL(148);
ISR_WRAPPER_DECL(149);
ISR_WRAPPER_DECL(150);
ISR_WRAPPER_DECL(151);
ISR_WRAPPER_DECL(152);
ISR_WRAPPER_DECL(153);
ISR_WRAPPER_DECL(154);
ISR_WRAPPER_DECL(155);
ISR_WRAPPER_DECL(156);
ISR_WRAPPER_DECL(157);
ISR_WRAPPER_DECL(158);
ISR_WRAPPER_DECL(159);
ISR_WRAPPER_DECL(160);
ISR_WRAPPER_DECL(161);
ISR_WRAPPER_DECL(162);
ISR_WRAPPER_DECL(163);
ISR_WRAPPER_DECL(164);
ISR_WRAPPER_DECL(165);
ISR_WRAPPER_DECL(166);
ISR_WRAPPER_DECL(167);
ISR_WRAPPER_DECL(168);
ISR_WRAPPER_DECL(169);
ISR_WRAPPER_DECL(170);
ISR_WRAPPER_DECL(171);
ISR_WRAPPER_DECL(172);
ISR_WRAPPER_DECL(173);
ISR_WRAPPER_DECL(174);
ISR_WRAPPER_DECL(175);
ISR_WRAPPER_DECL(176);
ISR_WRAPPER_DECL(177);
ISR_WRAPPER_DECL(178);
ISR_WRAPPER_DECL(179);
ISR_WRAPPER_DECL(180);
ISR_WRAPPER_DECL(181);
ISR_WRAPPER_DECL(182);
ISR_WRAPPER_DECL(183);
ISR_WRAPPER_DECL(184);
ISR_WRAPPER_DECL(185);
ISR_WRAPPER_DECL(186);
ISR_WRAPPER_DECL(187);
ISR_WRAPPER_DECL(188);
ISR_WRAPPER_DECL(189);
ISR_WRAPPER_DECL(190);
ISR_WRAPPER_DECL(191);
ISR_WRAPPER_DECL(192);
ISR_WRAPPER_DECL(193);
ISR_WRAPPER_DECL(194);
ISR_WRAPPER_DECL(195);
ISR_WRAPPER_DECL(196);
ISR_WRAPPER_DECL(197);
ISR_WRAPPER_DECL(198);
ISR_WRAPPER_DECL(199);
ISR_WRAPPER_DECL(200);
ISR_WRAPPER_DECL(201);
ISR_WRAPPER_DECL(202);
ISR_WRAPPER_DECL(203);
ISR_WRAPPER_DECL(204);
ISR_WRAPPER_DECL(205);
ISR_WRAPPER_DECL(206);
ISR_WRAPPER_DECL(207);
ISR_WRAPPER_DECL(208);
ISR_WRAPPER_DECL(209);
ISR_WRAPPER_DECL(210);
ISR_WRAPPER_DECL(211);
ISR_WRAPPER_DECL(212);
ISR_WRAPPER_DECL(213);
ISR_WRAPPER_DECL(214);
ISR_WRAPPER_DECL(215);
ISR_WRAPPER_DECL(216);
ISR_WRAPPER_DECL(217);
ISR_WRAPPER_DECL(218);
ISR_WRAPPER_DECL(219);
ISR_WRAPPER_DECL(220);
ISR_WRAPPER_DECL(221);
ISR_WRAPPER_DECL(222);
ISR_WRAPPER_DECL(223);
ISR_WRAPPER_DECL(224);
ISR_WRAPPER_DECL(225);
ISR_WRAPPER_DECL(226);
ISR_WRAPPER_DECL(227);
ISR_WRAPPER_DECL(228);
ISR_WRAPPER_DECL(229);
ISR_WRAPPER_DECL(230);
ISR_WRAPPER_DECL(231);
ISR_WRAPPER_DECL(232);
ISR_WRAPPER_DECL(233);
ISR_WRAPPER_DECL(234);
ISR_WRAPPER_DECL(235);
ISR_WRAPPER_DECL(236);
ISR_WRAPPER_DECL(237);
ISR_WRAPPER_DECL(238);
ISR_WRAPPER_DECL(239);
ISR_WRAPPER_DECL(240);
ISR_WRAPPER_DECL(241);
ISR_WRAPPER_DECL(242);
ISR_WRAPPER_DECL(243);
ISR_WRAPPER_DECL(244);
ISR_WRAPPER_DECL(245);
ISR_WRAPPER_DECL(246);
ISR_WRAPPER_DECL(247);
ISR_WRAPPER_DECL(248);
ISR_WRAPPER_DECL(249);
ISR_WRAPPER_DECL(250);
ISR_WRAPPER_DECL(251);
ISR_WRAPPER_DECL(252);
ISR_WRAPPER_DECL(253);
ISR_WRAPPER_DECL(254);
ISR_WRAPPER_DECL(255);

static isr_wrapper_t ISR_WRAPPERS[MAX_INTERRUPTS] = {
	ISR_WRAPPER_NAME(0),
	ISR_WRAPPER_NAME(1),
	ISR_WRAPPER_NAME(2),
	ISR_WRAPPER_NAME(3),
	ISR_WRAPPER_NAME(4),
	ISR_WRAPPER_NAME(5),
	ISR_WRAPPER_NAME(6),
	ISR_WRAPPER_NAME(7),
	ISR_WRAPPER_NAME(8),
	ISR_WRAPPER_NAME(9),
	ISR_WRAPPER_NAME(10),
	ISR_WRAPPER_NAME(11),
	ISR_WRAPPER_NAME(12),
	ISR_WRAPPER_NAME(13),
	ISR_WRAPPER_NAME(14),
	ISR_WRAPPER_NAME(15),
	ISR_WRAPPER_NAME(16),
	ISR_WRAPPER_NAME(17),
	ISR_WRAPPER_NAME(18),
	ISR_WRAPPER_NAME(19),
	ISR_WRAPPER_NAME(20),
	ISR_WRAPPER_NAME(21),
	ISR_WRAPPER_NAME(22),
	ISR_WRAPPER_NAME(23),
	ISR_WRAPPER_NAME(24),
	ISR_WRAPPER_NAME(25),
	ISR_WRAPPER_NAME(26),
	ISR_WRAPPER_NAME(27),
	ISR_WRAPPER_NAME(28),
	ISR_WRAPPER_NAME(29),
	ISR_WRAPPER_NAME(30),
	ISR_WRAPPER_NAME(31),
	ISR_WRAPPER_NAME(32),
	ISR_WRAPPER_NAME(33),
	ISR_WRAPPER_NAME(34),
	ISR_WRAPPER_NAME(35),
	ISR_WRAPPER_NAME(36),
	ISR_WRAPPER_NAME(37),
	ISR_WRAPPER_NAME(38),
	ISR_WRAPPER_NAME(39),
	ISR_WRAPPER_NAME(40),
	ISR_WRAPPER_NAME(41),
	ISR_WRAPPER_NAME(42),
	ISR_WRAPPER_NAME(43),
	ISR_WRAPPER_NAME(44),
	ISR_WRAPPER_NAME(45),
	ISR_WRAPPER_NAME(46),
	ISR_WRAPPER_NAME(47),
	ISR_WRAPPER_NAME(48),
	ISR_WRAPPER_NAME(49),
	ISR_WRAPPER_NAME(50),
	ISR_WRAPPER_NAME(51),
	ISR_WRAPPER_NAME(52),
	ISR_WRAPPER_NAME(53),
	ISR_WRAPPER_NAME(54),
	ISR_WRAPPER_NAME(55),
	ISR_WRAPPER_NAME(56),
	ISR_WRAPPER_NAME(57),
	ISR_WRAPPER_NAME(58),
	ISR_WRAPPER_NAME(59),
	ISR_WRAPPER_NAME(60),
	ISR_WRAPPER_NAME(61),
	ISR_WRAPPER_NAME(62),
	ISR_WRAPPER_NAME(63),
	ISR_WRAPPER_NAME(64),
	ISR_WRAPPER_NAME(65),
	ISR_WRAPPER_NAME(66),
	ISR_WRAPPER_NAME(67),
	ISR_WRAPPER_NAME(68),
	ISR_WRAPPER_NAME(69),
	ISR_WRAPPER_NAME(70),
	ISR_WRAPPER_NAME(71),
	ISR_WRAPPER_NAME(72),
	ISR_WRAPPER_NAME(73),
	ISR_WRAPPER_NAME(74),
	ISR_WRAPPER_NAME(75),
	ISR_WRAPPER_NAME(76),
	ISR_WRAPPER_NAME(77),
	ISR_WRAPPER_NAME(78),
	ISR_WRAPPER_NAME(79),
	ISR_WRAPPER_NAME(80),
	ISR_WRAPPER_NAME(81),
	ISR_WRAPPER_NAME(82),
	ISR_WRAPPER_NAME(83),
	ISR_WRAPPER_NAME(84),
	ISR_WRAPPER_NAME(85),
	ISR_WRAPPER_NAME(86),
	ISR_WRAPPER_NAME(87),
	ISR_WRAPPER_NAME(88),
	ISR_WRAPPER_NAME(89),
	ISR_WRAPPER_NAME(90),
	ISR_WRAPPER_NAME(91),
	ISR_WRAPPER_NAME(92),
	ISR_WRAPPER_NAME(93),
	ISR_WRAPPER_NAME(94),
	ISR_WRAPPER_NAME(95),
	ISR_WRAPPER_NAME(96),
	ISR_WRAPPER_NAME(97),
	ISR_WRAPPER_NAME(98),
	ISR_WRAPPER_NAME(99),
	ISR_WRAPPER_NAME(100),
	ISR_WRAPPER_NAME(101),
	ISR_WRAPPER_NAME(102),
	ISR_WRAPPER_NAME(103),
	ISR_WRAPPER_NAME(104),
	ISR_WRAPPER_NAME(105),
	ISR_WRAPPER_NAME(106),
	ISR_WRAPPER_NAME(107),
	ISR_WRAPPER_NAME(108),
	ISR_WRAPPER_NAME(109),
	ISR_WRAPPER_NAME(110),
	ISR_WRAPPER_NAME(111),
	ISR_WRAPPER_NAME(112),
	ISR_WRAPPER_NAME(113),
	ISR_WRAPPER_NAME(114),
	ISR_WRAPPER_NAME(115),
	ISR_WRAPPER_NAME(116),
	ISR_WRAPPER_NAME(117),
	ISR_WRAPPER_NAME(118),
	ISR_WRAPPER_NAME(119),
	ISR_WRAPPER_NAME(120),
	ISR_WRAPPER_NAME(121),
	ISR_WRAPPER_NAME(122),
	ISR_WRAPPER_NAME(123),
	ISR_WRAPPER_NAME(124),
	ISR_WRAPPER_NAME(125),
	ISR_WRAPPER_NAME(126),
	ISR_WRAPPER_NAME(127),
	ISR_WRAPPER_NAME(128),
	ISR_WRAPPER_NAME(129),
	ISR_WRAPPER_NAME(130),
	ISR_WRAPPER_NAME(131),
	ISR_WRAPPER_NAME(132),
	ISR_WRAPPER_NAME(133),
	ISR_WRAPPER_NAME(134),
	ISR_WRAPPER_NAME(135),
	ISR_WRAPPER_NAME(136),
	ISR_WRAPPER_NAME(137),
	ISR_WRAPPER_NAME(138),
	ISR_WRAPPER_NAME(139),
	ISR_WRAPPER_NAME(140),
	ISR_WRAPPER_NAME(141),
	ISR_WRAPPER_NAME(142),
	ISR_WRAPPER_NAME(143),
	ISR_WRAPPER_NAME(144),
	ISR_WRAPPER_NAME(145),
	ISR_WRAPPER_NAME(146),
	ISR_WRAPPER_NAME(147),
	ISR_WRAPPER_NAME(148),
	ISR_WRAPPER_NAME(149),
	ISR_WRAPPER_NAME(150),
	ISR_WRAPPER_NAME(151),
	ISR_WRAPPER_NAME(152),
	ISR_WRAPPER_NAME(153),
	ISR_WRAPPER_NAME(154),
	ISR_WRAPPER_NAME(155),
	ISR_WRAPPER_NAME(156),
	ISR_WRAPPER_NAME(157),
	ISR_WRAPPER_NAME(158),
	ISR_WRAPPER_NAME(159),
	ISR_WRAPPER_NAME(160),
	ISR_WRAPPER_NAME(161),
	ISR_WRAPPER_NAME(162),
	ISR_WRAPPER_NAME(163),
	ISR_WRAPPER_NAME(164),
	ISR_WRAPPER_NAME(165),
	ISR_WRAPPER_NAME(166),
	ISR_WRAPPER_NAME(167),
	ISR_WRAPPER_NAME(168),
	ISR_WRAPPER_NAME(169),
	ISR_WRAPPER_NAME(170),
	ISR_WRAPPER_NAME(171),
	ISR_WRAPPER_NAME(172),
	ISR_WRAPPER_NAME(173),
	ISR_WRAPPER_NAME(174),
	ISR_WRAPPER_NAME(175),
	ISR_WRAPPER_NAME(176),
	ISR_WRAPPER_NAME(177),
	ISR_WRAPPER_NAME(178),
	ISR_WRAPPER_NAME(179),
	ISR_WRAPPER_NAME(180),
	ISR_WRAPPER_NAME(181),
	ISR_WRAPPER_NAME(182),
	ISR_WRAPPER_NAME(183),
	ISR_WRAPPER_NAME(184),
	ISR_WRAPPER_NAME(185),
	ISR_WRAPPER_NAME(186),
	ISR_WRAPPER_NAME(187),
	ISR_WRAPPER_NAME(188),
	ISR_WRAPPER_NAME(189),
	ISR_WRAPPER_NAME(190),
	ISR_WRAPPER_NAME(191),
	ISR_WRAPPER_NAME(192),
	ISR_WRAPPER_NAME(193),
	ISR_WRAPPER_NAME(194),
	ISR_WRAPPER_NAME(195),
	ISR_WRAPPER_NAME(196),
	ISR_WRAPPER_NAME(197),
	ISR_WRAPPER_NAME(198),
	ISR_WRAPPER_NAME(199),
	ISR_WRAPPER_NAME(200),
	ISR_WRAPPER_NAME(201),
	ISR_WRAPPER_NAME(202),
	ISR_WRAPPER_NAME(203),
	ISR_WRAPPER_NAME(204),
	ISR_WRAPPER_NAME(205),
	ISR_WRAPPER_NAME(206),
	ISR_WRAPPER_NAME(207),
	ISR_WRAPPER_NAME(208),
	ISR_WRAPPER_NAME(209),
	ISR_WRAPPER_NAME(210),
	ISR_WRAPPER_NAME(211),
	ISR_WRAPPER_NAME(212),
	ISR_WRAPPER_NAME(213),
	ISR_WRAPPER_NAME(214),
	ISR_WRAPPER_NAME(215),
	ISR_WRAPPER_NAME(216),
	ISR_WRAPPER_NAME(217),
	ISR_WRAPPER_NAME(218),
	ISR_WRAPPER_NAME(219),
	ISR_WRAPPER_NAME(220),
	ISR_WRAPPER_NAME(221),
	ISR_WRAPPER_NAME(222),
	ISR_WRAPPER_NAME(223),
	ISR_WRAPPER_NAME(224),
	ISR_WRAPPER_NAME(225),
	ISR_WRAPPER_NAME(226),
	ISR_WRAPPER_NAME(227),
	ISR_WRAPPER_NAME(228),
	ISR_WRAPPER_NAME(229),
	ISR_WRAPPER_NAME(230),
	ISR_WRAPPER_NAME(231),
	ISR_WRAPPER_NAME(232),
	ISR_WRAPPER_NAME(233),
	ISR_WRAPPER_NAME(234),
	ISR_WRAPPER_NAME(235),
	ISR_WRAPPER_NAME(236),
	ISR_WRAPPER_NAME(237),
	ISR_WRAPPER_NAME(238),
	ISR_WRAPPER_NAME(239),
	ISR_WRAPPER_NAME(240),
	ISR_WRAPPER_NAME(241),
	ISR_WRAPPER_NAME(242),
	ISR_WRAPPER_NAME(243),
	ISR_WRAPPER_NAME(244),
	ISR_WRAPPER_NAME(245),
	ISR_WRAPPER_NAME(246),
	ISR_WRAPPER_NAME(247),
	ISR_WRAPPER_NAME(248),
	ISR_WRAPPER_NAME(249),
	ISR_WRAPPER_NAME(250),
	ISR_WRAPPER_NAME(251),
	ISR_WRAPPER_NAME(252),
	ISR_WRAPPER_NAME(253),
	ISR_WRAPPER_NAME(254),
	ISR_WRAPPER_NAME(255)
};
















